//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string CustName { get; set; }
        public bool IsValid { get; set; }
        public System.DateTime ValidTill { get; set; }
        public System.DateTime EnteredOnDate { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public string CustAddress { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string CustCode { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string password { get; set; }
        public int dealerid { get; set; }
        public Nullable<decimal> dealerprice { get; set; }
        public Nullable<decimal> customerprice { get; set; }
    }
}
