//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IdCardDataManagerEntities1 : DbContext
    {
        public IdCardDataManagerEntities1()
            : base("name=IdCardDataManagerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<softwareoption> softwareoptions { get; set; }
        public virtual DbSet<ParentLogin> ParentLogins { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Dealer> Dealers { get; set; }
        public virtual DbSet<renewal> renewals { get; set; }
        public virtual DbSet<StoreAPK> StoreAPKs { get; set; }
        public virtual DbSet<session_master> session_master { get; set; }
    }
}
