//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentLogin
    {
        public int id { get; set; }
        public Nullable<int> schoolid { get; set; }
        public string username { get; set; }
        public string upassword { get; set; }
        public bool isactive { get; set; }
        public string schoolname { get; set; }
    }
}
