//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class renewal
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<long> mobile { get; set; }
        public Nullable<System.DateTime> current_validity { get; set; }
        public Nullable<System.DateTime> new_validity { get; set; }
        public Nullable<decimal> customer_amt { get; set; }
        public Nullable<decimal> dealer_amt { get; set; }
        public Nullable<bool> paid { get; set; }
        public Nullable<System.DateTime> renewal__date { get; set; }
    }
}
