//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class School
    {
        public int SchoolId { get; set; }
        public string SchoolName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Logo { get; set; }
        public string SchoolCode { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> updatedby { get; set; }
        public string password { get; set; }
    public HttpPostedFileBase LogoUpload { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
