//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class softwareoption
    {
        public bool StName { get; set; }
        public bool FatherName { get; set; }
        public bool MotherName { get; set; }
        public bool Dob { get; set; }
        public bool Mobile { get; set; }
        public bool Address { get; set; }
        public bool OptedConveyance { get; set; }
        public bool ClassName { get; set; }
        public bool SectonName { get; set; }
        public bool Session { get; set; }
        public bool Photo { get; set; }
        public bool Res1 { get; set; }
        public bool Res2 { get; set; }
        public int StSchool_SchoolId { get; set; }
        public bool admno { get; set; }
        public int ID { get; set; }
        public bool driver { get; set; }
        public bool conveyance { get; set; }
        public bool stop { get; set; }
        public bool designation { get; set; }
        public bool driver_mobile { get; set; }
        public bool RollNo { get; set; }
        public bool house { get; set; }
        public bool emergency_no { get; set; }
        public bool blood_group { get; set; }
    }
}
