//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Student
    {
        public int StudentId { get; set; }
        public string AdmNo { get; set; }
        public string StName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Dob { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public bool OptedConveyance { get; set; }
        public string ClassName { get; set; }
        public string SectonName { get; set; }
        public string Session { get; set; }
        public string Photo { get; set; }
        public string Res1 { get; set; }
        public string Res2 { get; set; }
        public bool ReviewedBySchool { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public bool NeedUpdation { get; set; }
        public bool AllCorrect { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> StSchool_SchoolId { get; set; }
        public Nullable<int> Batch { get; set; }
        public string Excel_Photo { get; set; }
        public bool IsPhotoUpload { get; set; }
        public string conveyance { get; set; }
        public string stop { get; set; }
        public string driver { get; set; }
        public string driver_mobile { get; set; }
        public string designation { get; set; }
        public string rollno { get; set; }
        public string house { get; set; }
        public Nullable<long> emergency_no { get; set; }
        public string bloodgroup { get; set; }
        public int Size { get; set; }
        public HttpPostedFileBase PhotoUpload { get; set; }
        public List<session_master> sessionlist { get; set; }
        public virtual School School { get; set; }
    }
}
